name: SCP Test

on:
  workflow_dispatch:

jobs:
  test-scp:
    runs-on: windows-latest
    steps:
      - name: Create a test file 
        run: |
          echo "This is a test file." > testfile.txt
          echo "version: 1.0.7" > latest.yml
          echo "files:" >> latest.yml
          echo "  - url: test.exe" >> latest.yml
          echo "    sha512: 3tx3ugvOwH2YISic6SNsyndVU7sZ1g5yZkA823fvbmZma34v9A3FydTO2Qf7F0ZomEKROEsuO5IvAe+wqkHGdA==" >> latest.yml    
        shell: pwsh

      - name: Install WinSCP
        run: |
          choco install winscp

      - name: SCP file using WinSCP
        env:
          SCP_PASSWORD: ${{ secrets.WIN_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.WIN_SERVER_IP }}
          REMOTE_USER: ${{ secrets.WIN_SERVER_USER }}
          REMOTE_PATH: ${{ secrets.REMOTE_SIGN_PATH }}/test.exe
          HOST_KEY: ${{ secrets.HOST_KEY }}
          FILE_TO_UPLOAD: 'testfile.txt'
          REMOTE_SCRIPT_PATH: "${{ secrets.REMOTE_SIGN_SCRIPT }} ${{ secrets.REMOTE_SIGN_PATH }}/Chat2DB-Pro-1.0.6.exe"
          LOCAL_DOWNLOAD_PATH: '${{ github.workspace }}/test.exe'
        run: |
          winscp.com /log=winscp.log /command `
            "option batch abort" `
            "option confirm off" `
            "open scp://${{ env.REMOTE_USER }}:${{ env.SCP_PASSWORD }}@${{ env.REMOTE_HOST }} -hostkey=*" `
            "get ${env:REMOTE_PATH} ${env:LOCAL_DOWNLOAD_PATH}" `
            "exit"

      # 修改windows加签后的yml文件
      - name: Calculate file hash
        if: ${{ runner.os == 'Windows' }}
        id: hash
        run: |
          $hash = (CertUtil -hashfile testfile.txt SHA512)[1] -replace ' ',''
          $base64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($hash))
          echo "::set-output name=sha512_base64::$base64"

      # 安装yq解析yml
      - name: Install yq
        if: ${{ runner.os == 'Windows' }}
        run: |
          Invoke-WebRequest -Uri "https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_windows_amd64.exe" -OutFile "yq.exe"
          New-Item -Path "C:\bin" -ItemType Directory -Force
          Move-Item -Path "yq.exe" -Destination "C:\bin\yq.exe"
        shell: powershell

      - name: Extract, replace, and print hash value
        if: ${{ runner.os == 'Windows' }}
        run: |
          # Extract and print the old hash value
          $old_hash = & C:\bin\yq.exe e '.sha512' test.exe
          Write-Output "Old Hash: $old_hash"
          Write-Output "New Hash: $new_hash"
      
          # Update the yaml file with the new hash
          & C:\bin\yq.exe e ".sha512 = \"$new_hash\"" -i latest.yml
          
          # Optionally, update hash in nested structure under 'files'
          & C:\bin\yq.exe e ".files[0].sha512 = \"$new_hash\"" -i latest.yml
        shell: powershell
        env:
          new_hash: ${{ steps.hash.outputs.sha512_base64 }}
