name: SCP Test

on:
  push:
    branches:
    - "scp_test"
  workflow_dispatch:

jobs:
  test-scp:
    runs-on: ubuntu-latest
    steps:
      # 发送到飞书
      - name: Send feishu message
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_WEBHOOK }}
          msg_type: post
          content: |
            {
              "zh_cn": {
                "title": "${{ secrets.TEST_PRODUCT_NAME }}-${{ matrix.file_name }}-打包完成通知",
                "content": [
                  [
                    {
                      "tag": "text",
                      "text": "${{ secrets.TEST_PRODUCT_NAME }}-${{ matrix.file_name }}-打包完成通知\n"
                    }
                  ],
                  [
                    {
                      "tag": "text",
                      "text": "任务id："
                    },
                    {
                      "tag": "a",
                      "text": "${{ github.run_id }}",
                      "href": "https://github.com/juliet0416/cicd-test/actions/runs/${{ github.run_id }}"
                    }
                  ],
                  [
                    {
                      "tag": "text",
                      "text": "下载地址：${{secrets.CDN_URL}}/test/${{ secrets.TEST_PRODUCT_NAME }}-${{ matrix.file_name }}"
                    }
                  ]
                ]
              }
            }
