name: SCP Test

on:
  push:
    branches:
    - "scp_test"
  workflow_dispatch:

jobs:
  test-scp:
    runs-on: windows-latest
    steps:
      # Install jre Windows
      - name: Install Jre for Windows
        if: ${{ runner.os == 'Windows' }}
        uses: actions/setup-java@main
        with:
          java-version: "17"
          distribution: "temurin"
          java-package: "jre"

      # java.security open tls1 Windows
      - name: Enable tls1
        if: ${{ runner.os == 'Windows' }}
        run: |
          # sed -i '' "s/\(^jdk.tls.disabledAlgorithms=\)\(.*\)\( TLSv1, TLSv1.1,\)\(.*\)/\1\2\4/" "${{ env.JAVA_HOME }}/conf/security/java.security"
          $filePath = "${{ env.JAVA_HOME }}\conf\security\java.security"
          $content = Get-Content $filePath -Raw
          $updatedContent = $content -replace '(?s)(jdk.tls.disabledAlgorithms\s*=\s*)(.*?)(\s*TLSv1,\s*TLSv1\.1,)(.*?)(?=[,\r\n])', '$1$2$4'


          $updatedContent | Set-Content $filePath
          # 在修改前打印文件的内容看看是否正确加载
          Write-Output "Original content:"
          Write-Output $content
          
          # 打印修改后的内容确认替换是否生效
          Write-Output "Updated content:"
          Write-Output $updatedContent

